version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /mlops_suleev/main.py
    volumes:
      - .:/mlops_suleev
    ports:
      - "0.0.0.0:5000:5000"